# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: YFWu's Blog
email: yfwu@yfwu.org
description: > # this means to ignore newlines until "baseurl:"
  在遙遠的邊陲小島住著一個不愛吃魚愛做夢的捕魚人
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://yfwu.github.io" # the base hostname & protocol for your site
twitter_username: yfw3u
github_username: yfwu

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics:
disqus_shortname:
# used this for post_excerpt at index_page
# excerpt_separator: <!--description-->

plugins:
  - jekyll-seo-tag